---
# Ansible playbook for configuring macOS with ansible-pull
# Run with: ansible-pull -U <repo-url> local.yml
#
# Variables are defined in group_vars/local.yml
- hosts: local
  connection: local
  become: false
  gather_facts: true
  
  roles:
    - base
    - homebrew