---
# Ansible playbook for configuring macOS with ansible-pull
# Run with: ansible-pull -U <repo-url> local.yml
- hosts: local
  connection: local
  become: false
  
  vars:
    homebrew_packages:
      - ansible-lint
      - gh
      - git
  
  tasks:
    - name: Ensure Homebrew is installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check
      tags: homebrew
    
    - name: Display Homebrew status
      debug:
        msg: "Homebrew is {{ 'installed' if homebrew_check.stat.exists else 'not installed' }}"
      tags: homebrew
    
    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ homebrew_packages }}"
        state: present
      when: homebrew_check.stat.exists
      tags: homebrew
    
    - name: Install Homebrew cask applications
      community.general.homebrew_cask:
        name: "{{ homebrew_cask_packages }}"
        state: present
      when: homebrew_check.stat.exists
      tags: homebrew
  
  roles:
    - base